import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

/*
 * esbuild 构建配置 | esbuild build configuration
 * 开发模式：node esbuild.config.mjs（启用 watch + inline sourcemap）
 * 生产模式：node esbuild.config.mjs production（minify，无 sourcemap）
 * Dev mode: node esbuild.config.mjs (watch + inline sourcemap)
 * Production mode: node esbuild.config.mjs production (minify, no sourcemap)
 */

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
